services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend

    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
